GET http://localhost:3000/facade

###
POST http://localhost:3000/facade
Content-Type: application/json

{"message" : "msg2"}
###
POST http://localhost:3000/facade
Content-Type: application/json

{"message" : "i deleted the facade so now i have to use json"}
